name: Build & Test

on:
  push:
  pull_request:

jobs:
  build-and-test-windows:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: git pull
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Verify Python installation
      run: |
        python --version
        where python
        python -m pip install --upgrade pip setuptools wheel

    - name: microsoft/setup-msbuild@v2
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '17.0'   # VS 2022

    - name: Locate Python
      shell: pwsh
      run: |
        $py = python -c "import sys; print(sys.base_prefix)"
        echo "PYTHONROOT=$py" >> $env:GITHUB_ENV

    - name: msbuild src/embeddings.vcxproj /p:Configuration=${{ matrix.configuration }} /p:Platform=x64
      shell: cmd
      run: |
        msbuild src/embeddings.vcxproj ^
          /p:Configuration=${{ matrix.configuration }} ^
          /p:Platform=x64 ^
          /p:PythonIncludeDir="$env:PYTHONROOT\include" ^
          /p:PythonLibDir="$env:PYTHONROOT\libs" ^

    - name: dir /s /b *.dll *.pyd *.exe
      run: |
        dir /s /b *.dll *.pyd *.exe

    - name: actions/upload-artifact@v4
      uses: actions/upload-artifact@v4
      with:
        name: embeddings-${{ matrix.configuration }}
        path: |
          **/${{ matrix.configuration }}/*.dll
          **/${{ matrix.configuration }}/*.pyd